name: CI/CD for Dockerized Streamlit App

on:
  push:
    branches:
      - main  # Runs the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Runs the workflow on pull requests to the main branch

jobs:
  dockerbuild:
    runs-on: ubuntu-latest  # Runs the job on Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from your GitHub repository

      - name: Set up Docker Buildx (for multi-platform support)
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for building images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub with credentials from GitHub Secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Access Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Access Docker Hub password from secrets

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest .  # Build the Docker image with the tag

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest  # Push the built image to Docker Hub

  # Optional: Run tests if you have test cases in your project
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Use Python 3.11 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      - name: Run tests
        run: |
          pytest -v  # If you have pytest tests, this runs them. Modify if needed.

