name: CI/CD for Dockerized Streamlit App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dockerbuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build The Docker Image
        run: docker build . --file Dockerfile --tag workflow-test:$(date +%s)

  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit  # Ensures Streamlit is installed
          pip install pytest  # If you're running tests with pytest

      - name: Run tests
        run: |
          pytest -v

  build-and-publish:
    needs: build-and-test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (if needed for multi-platform)
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Make sure Dockerfile is correct
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

      - name: Image digest
        run: echo ${{ steps.build-and-publish.outputs.digest }}
